import { Geist, Geist_Mono } from "next/font/google";
import Navbar from '../components/Navbar';
import { AuthProvider } from '../contexts/AuthContext';
import { SocketProvider } from '../contexts/SocketContext';
import './globals.css';
import { Toaster } from 'react-hot-toast';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <AuthProvider>
          <SocketProvider>
            <Navbar />
            <Toaster position="top-right" toastOptions={{
    success: {
      duration: 3000,
    },
    error: {
      duration: 5000,
    },
  }} />
            {children}
          </SocketProvider>
      </AuthProvider>
      </body>
    </html>
  );
}

